#pragma kernel Update

struct TileInfo {

};

int pixPerTile;
int2 tileDims;
float t;

RWTexture2D<float4> _Texture;

[numthreads(8,8,1)]
void Update(uint3 id : SV_DispatchThreadID) {
    int2 tile = id.xy / pixPerTile;
    float2 tileUV = float2(id.xy - tile * pixPerTile) / pixPerTile;

    float4 color = float4(0, 0, 0, 0);
    if(tileUV.x < 0.03 || tileUV.x > 0.97 || tileUV.y < 0.03 || tileUV.y > 0.97) {
        color = float4(1, 1, 1, 0.2);
    }

    _Texture[id.xy] = color;
}
